# Generated by Django 4.0.3 on 2022-03-07 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0002_alter_task_created_at_alter_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
