# Generated by Django 4.0.3 on 2022-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk', '0002_remove_book_pagecount_remove_book_publisheddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default='bk/thumbnail.jpg', upload_to='bk/'),
        ),
    ]
